name: Maven Central publishing

on:
  workflow_dispatch:

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Receiving PGP key"
        run: |
          sudo gpg --keyserver keys.openpgp.org --recv-keys 31A930A7A113E5646D6A9813767BF2724358B6E0

      - name: "Publishing"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          chmod +x ./gradlew
          ./gradlew publish