name: Maven Central publishing

on:
  workflow_dispatch:

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Importing GPG key"
        run: |
          sudo gpg --import secring.gpg 

      - name: "Publishing"
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          chmod +x ./gradlew
          ./gradlew publish closeAndReleaseSonatypeStagingRepository